version: '3.4'

services:
    order.api:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
        ports:
        - "7000:80"
        - "7001:443"
        networks:
        - net_backend
        restart: no
        depends_on:
        - s_sqlserver
        - s_rabbitmq
        mem_limit: 1g
        external_links:
        - s_rabbitmq

    payment.api:
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        ports:
        - "7002:80"
        - "7003:443"
        depends_on:
        - s_rabbitmq
        networks:
        - net_backend
        restart: no
        mem_limit: 1g
        external_links:
        - s_rabbitmq
       
    stock.api:
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        ports:
        - "7004:80"
        - "7005:443"
        networks:
        - net_backend
        restart: no
        depends_on:
        - s_sqlserver
        - s_rabbitmq
        mem_limit: 1g
        external_links:
        - s_rabbitmq

    saga.state.machine:
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        ports:
        - "7006:80"
        depends_on:
        - s_rabbitmq
        - s_sqlserver
        networks:
        - net_backend
        restart: no
        mem_limit: 1g
        external_links:
        - s_rabbitmq

    s_sqlserver:
        user: root
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: Test123!_
        ports:
        - "1433:1433"
        volumes:
        - sqlserver_data:/var/opt/mssql/data
        - sqlserver_log:/var/opt/mssql/log
        networks:
        - net_backend
        mem_limit: 2g
    
    s_rabbitmq:
        ports:
        - 5672:5672
        - 15672:15672
        volumes:
        - rabbitmq:/var/lib/rabbitmq
        networks:
        - net_backend
        restart: on-failure
        environment:
            RABBITMQ_HOST: localhost
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

networks:
    net_backend:
        driver: bridge

volumes:
    rabbitmq:
    sqlserver_data:
    sqlserver_log:
